### ISSUE TITLE
添加 ObjectPool 的统计功能

### ISSUE THREAD

**Issue by hevake** [cpp-main/cpp-tbox#19]
申请次数，释放次数。malloc次数等。

**Comment by Barenboim** [comment]
看了一下代码，这个ObjectPool还不是线程安全的。我感觉性能可能不如直接new/delete啊。

**Comment by hevake** [comment]
实测是有new与delete好的，耗时是new与delete的1/3。正是因为它不加锁，所以会快。
在基于tbox框架开发，大部分都是同一个线程中的内部操作，没有加锁的必要。

**Comment by hevake** [comment]
> 

```
#include <tbox/base/object_pool.hpp>
#include <tbox/util/time_counter.h>

struct MyData {
    char array[1500];
};

int main() {
    int times = 100000;
    {
        SetTimeCounter();
        for (int i = 0; i < times; ++i) {
            auto *p1 = new MyData;
            auto *p2 = new MyData;
            delete p1;
            delete p2;
        }
    }
    {
        tbox::ObjectPool<MyData> pool;
        SetTimeCounter();
        for (int i = 0; i < times; ++i) {
            auto *p1 = pool.alloc();
            auto *p2 = pool.alloc();
            pool.free(p1);
            pool.free(p2);
        }
    }
}
```
![图片](https://github.com/cpp-main/cpp-tbox/assets/79179087/a7c9ccca-4cc4-4ef5-a7ee-8761b3afbd76)

**Comment by Barenboim** [comment]
噢噢，不涉及多线程那你这么做肯定会快。还有一个问题就是释放的位置也必要知道对象的具体类型，这样就失去了抽象性了。

**Comment by hevake** [comment]
> 噢噢，不涉及多线程那你这么做肯定会快。还有一个问题就是释放的位置也必要知道对象的具体类型，这样就失去了抽象性了。

从哪个池子alloc()，就从哪里free()。
目前使用中，没有遇到这个问题。能说有一你具体的实用场景吗？

**Comment by Barenboim** [comment]
例如B从A派生，那么分配的类型是B，但很多场景下，可能是通过A类型指针释放对象的。这种情况下，就需要把A *转成B *来释放吧？我的意思是这种情况下失去抽象性。

**Comment by hevake** [comment]
done.
