### ISSUE TITLE
cannot find -levent_core -lev问题

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [cpp-main/cpp-tbox#23]
![61689661346_ pic](https://github.com/cpp-main/cpp-tbox/assets/28779327/0b554838-b666-4600-afaf-0574df0f42a9)

**Comment by hevake** [comment]
这个问题是没有安装libevent与libev，直接make引起的。
之前cpp-tbox是有依赖这两个库，后来这两个库被替代了，已不再依赖了。
但是在个别的Makefile中，忘了删除对应的库链接。

临时解决办法：
修改以下三个文件：
modules/coroutine/Makefile
modules/terminal/Makefile
modules/mqtt/Makefile

将以下红框中的内容删除：
<img width="526" alt="e4c230d7cadcc7374e0c096636849a8" src="https://github.com/cpp-main/cpp-tbox/assets/79179087/21514d38-6f1d-4eb8-a703-c670fca9db6d">

重新make即可。
