### ISSUE TITLE
有符号char右移出错

### ISSUE THREAD

**Issue by lzl200110** [cpp-main/cpp-tbox#46]
modules/http/url_test.cpp  line37 
 ```EXPECT_EQ(UrlEncode("\xA0\xB0"), R"(%A0%B0)")``` 调用了UrlEncode,`\xA0 \xB0`对应160(-96)和176(-80),在执行
```url_str.push_back(char_to_hex[c >> 4])```右移时变成-6和-5,应改成```url_str.push_back(char_to_hex[static_cast<unsigned char>(c) >> 4])```

**Comment by hevake** [comment]
已修复。
